apiVersion: v1
kind: ConfigMap
metadata:
  #  matches the spring app name as defined in application.yml
  name: usermicro
data:
  #  must be named 'application.yaml' or be the only key in this config
  #  refer to Spring Cloud Kubernetes Config documentation or source code
  application.yaml: |
    app:
      config: Inside Kube Cluster Config.
    bean:
      message: This is coming from K8s Cluster.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-variable-config
data:
  ENVIRONMENT_CONFIG: can read this

