apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermicro
  template:
    metadata:
      labels:
        app: usermicro
    spec:
      serviceAccountName: spring-service-account
      containers:
      - name: usermicro
        image: asimarunava/usermicro
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
          limits:
            cpu: 2.0
            memory: 1Gi
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: ENVIRONMENT_CONFIG
            valueFrom:
              configMapKeyRef:
                name: environment-variable-config
                key: ENVIRONMENT_CONFIG
