apiVersion: v1
kind: Service
metadata:
  name: usermicro-service
  labels:
    name: usermicro-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: usermicro
  type: NodePort