apiVersion: v1
kind: Service
metadata:
  name: usermicro-service
  labels:
    name: usermicro-service
spec:
  selector:
    app: usermicro
  type: NodePort
  ports:
    - name: springboot
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 8081
      targetPort: 8081
