apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spring-service-account-role
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - configmaps
    - secrets
    - services
    - namespaces
    verbs:
    - get
    - watch
    - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-service-account-role-binding
  namespace: default

roleRef:
  kind: Role
  name: spring-service-account-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spring-service-account
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-service-account
  namespace: default