apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: asimarunava/usermicro
      docker:
        dockerfile: Dockerfile
  local:
    push: true

deploy:
  kubectl:
    manifests:
      - k8s-*